# Generated by Django 5.0.6 on 2026-07-19 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=100)),
                ('lmp_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='accounts.chwprofile')),
            ],
        ),
    ]
