# Generated by Django 5.0.6 on 2026-07-19 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('outcome', models.CharField(choices=[('ATTENDED', 'Attended'), ('MISSED', 'Missed'), ('DANGER_SIGNS', 'Danger Signs Noted')], max_length=20)),
                ('chw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_logs', to='accounts.chwprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DangerSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(max_length=100)),
                ('visit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danger_signs', to='visits.visitlog')),
            ],
        ),
    ]
