# Generated by Django 5.0.6 on 2026-07-19 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANCSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_1_date', models.DateField()),
                ('visit_2_date', models.DateField()),
                ('visit_3_date', models.DateField()),
                ('visit_4_date', models.DateField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anc_schedule', to='patients.patient')),
            ],
        ),
    ]
